import os
import unittest

import numpy as np

# The local PySC2 package ships protobuf stubs generated by an older protoc.
os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")

from mat.envs.starcraft2.StarCraft2_Env import StarCraft2Env


class SMACEnemyInfoSharingTest(unittest.TestCase):
    def test_observer_ids_exclude_neighbors_when_sharing_is_disabled(self):
        env = StarCraft2Env.__new__(StarCraft2Env)
        communication_matrix = np.array(
            [[False, True, False], [True, False, True], [False, True, False]]
        )

        env.share_enemy_info_with_neighbors = True
        self.assertEqual(env.get_enemy_observer_ids(0, communication_matrix), [0, 1])

        env.share_enemy_info_with_neighbors = False
        self.assertEqual(env.get_enemy_observer_ids(0, communication_matrix), [0])

    def test_enemy_visibility_columns_follow_the_flag(self):
        env = StarCraft2Env.__new__(StarCraft2Env)
        env.n_agents = 2
        env.n_enemies = 1
        env.enemies = {0: object()}
        communication_matrix = np.array([[False, True], [True, False]])
        env.get_agent_communication_matrix = lambda: communication_matrix
        env.get_alive_agent_ids = lambda: [0, 1]
        env.is_enemy_visible_to_agent = (
            lambda observer_id, enemy_id: observer_id == 1 and enemy_id == 0
        )

        env.share_enemy_info_with_neighbors = True
        shared_visibility = env.get_visibility_matrix()
        self.assertTrue(shared_visibility[0, 2])

        env.share_enemy_info_with_neighbors = False
        strict_visibility = env.get_visibility_matrix()
        self.assertFalse(strict_visibility[0, 2])
        self.assertTrue(strict_visibility[1, 2])


if __name__ == "__main__":
    unittest.main()
