import os
import unittest
from types import SimpleNamespace

import numpy as np

# The local PySC2 package ships protobuf stubs generated by an older protoc.
os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")

from mat.envs.starcraft2.StarCraft2_Env import StarCraft2Env
from mat.utils.graph_utils import assert_connected_ally_topologies


class SMACEnemyInfoSharingTest(unittest.TestCase):
    def test_observer_ids_exclude_neighbors_when_sharing_is_disabled(self):
        env = StarCraft2Env.__new__(StarCraft2Env)
        communication_matrix = np.array(
            [[False, True, False], [True, False, True], [False, True, False]]
        )

        env.share_enemy_info_with_neighbors = True
        self.assertEqual(env.get_enemy_observer_ids(0, communication_matrix), [0, 1])

        env.share_enemy_info_with_neighbors = False
        self.assertEqual(env.get_enemy_observer_ids(0, communication_matrix), [0])

    def test_enemy_visibility_columns_follow_the_flag(self):
        env = StarCraft2Env.__new__(StarCraft2Env)
        env.n_agents = 2
        env.n_enemies = 1
        env.enemies = {0: object()}
        communication_matrix = np.array([[False, True], [True, False]])
        env.get_agent_communication_matrix = lambda: communication_matrix
        env.get_alive_agent_ids = lambda: [0, 1]
        env.is_enemy_visible_to_agent = (
            lambda observer_id, enemy_id: observer_id == 1 and enemy_id == 0
        )

        env.share_enemy_info_with_neighbors = True
        shared_visibility = env.get_visibility_matrix()
        self.assertTrue(shared_visibility[0, 2])

        env.share_enemy_info_with_neighbors = False
        strict_visibility = env.get_visibility_matrix()
        self.assertFalse(strict_visibility[0, 2])
        self.assertTrue(strict_visibility[1, 2])

    def test_enemy_visibility_uses_standard_range_not_ally_range(self):
        env = StarCraft2Env.__new__(StarCraft2Env)
        env._unit_sight_range = 2.0
        ally = SimpleNamespace(health=1, pos=SimpleNamespace(x=0.0, y=0.0))
        enemy = SimpleNamespace(health=1, pos=SimpleNamespace(x=8.0, y=0.0))
        env.get_unit_by_id = lambda agent_id: ally
        env.enemies = {0: enemy}

        self.assertEqual(env.unit_sight_range(0), 2.0)
        self.assertTrue(env.is_enemy_visible_to_agent(0, 0))
        enemy.pos.x = 9.0
        self.assertFalse(env.is_enemy_visible_to_agent(0, 0))

    def test_strict_attack_visibility_uses_enemy_sight_range(self):
        env = StarCraft2Env.__new__(StarCraft2Env)
        env._unit_sight_range = 2.0
        env.strict_attack_visibility = True

        self.assertTrue(env.target_is_action_visible(0, 1.5, 6.0))
        self.assertTrue(env.target_is_action_visible(0, 3.0, 6.0))
        self.assertFalse(env.target_is_action_visible(0, 7.0, 6.0))

    def test_legacy_attack_visibility_can_be_restored(self):
        env = StarCraft2Env.__new__(StarCraft2Env)
        env._unit_sight_range = 2.0
        env.strict_attack_visibility = False

        self.assertTrue(env.target_is_action_visible(0, 3.0, 6.0))
        self.assertFalse(env.target_is_action_visible(0, 7.0, 6.0))

    def test_connected_ally_topology_validation(self):
        adjacency = np.array(
            [[[False, True, False], [True, False, True], [False, True, False]]]
        )
        alive_mask = np.array([[True, True, True]])

        assert_connected_ally_topologies(adjacency, alive_mask)

    def test_disconnected_ally_topology_validation_fails(self):
        adjacency = np.array(
            [[[False, True, False], [True, False, False], [False, False, False]]]
        )
        alive_mask = np.array([[True, True, True]])

        with self.assertRaisesRegex(RuntimeError, "Disconnected ally"):
            assert_connected_ally_topologies(adjacency, alive_mask)

    def test_dead_agents_are_excluded_from_topology_validation(self):
        adjacency = np.array(
            [[[False, True, False], [True, False, False], [False, False, False]]]
        )
        alive_mask = np.array([[True, True, False]])

        assert_connected_ally_topologies(adjacency, alive_mask)


if __name__ == "__main__":
    unittest.main()
